---
# tasks file for roles/webserver

- name: Upload application file
  copy:
    src: ../files/index.php
    dest: "{{ path_to_app }}"
    mode: 0755

- name: Create simple info page
  copy:
    dest: "{{ path_to_app }}/info.php"
    content: "<h1> Info about our webserver {{ ansible_hostname }}. These are Changes!</h1>"

- name: Configure php.ini file
  lineinfile:
    path: /etc/php/7.3/apache2/php.ini
    regexp: ^short_open_tag
    line: "short_open_tag=on"
  notify: restart apache