# check-status.yml
---
  - hosts: webservers:loadbalancers
    become: true
    tasks:
      - name: Check status of apache
        command: service apache2 status
        args:
          warn: no
        changed_when: false
      
      - name: This will not fail
        command: /bin/false
        ignore_errors: yes